FORMAT: 1A
HOST: http://api.catarse.me

# Catarse API
Catarse API is a service to provide all Catarse funcionality through a nice API.

## Allowed HTTPs requests:

  - `POST` - Creates or updates a resource
  - `PATCH` - Updates a resource
  - `GET` - Retrieves a resource or list of resources
  - `DELETE` - Delete a resource


## Typical Server Responses

  - `200` OK - The request was successful (some API calls may return 201 instead).
  - `201` Created - The request was successful and a resource was created.
  - `204` No Content - The request was successful but there is no representation to return (that is, the response is empty).
  - `400` Bad Request - The request could not be understood or was missing required parameters.
  - `401` Unauthorized - Authentication failed.
  - `403` Forbidden - User does not have permissions for the requested operation.
  - `404` Not Found - Resource was not found.
  - `405` Method Not Allowed - Requested method is not supported for the specified resource.
  - `422` Unprocessable Entity - The resource may contain validation errors.
  - `503` Service Unavailable - The service is temporary unavailable (e.g. scheduled Platform Maintenance). Try again later.

# Group Users
Users related resources of the **Catarse API**

## Users Collection [/users]

### List users [GET]

Requires the user to be an admin.

+ Request

    + Header

            Authorization: Token your-token-here

    + Body

            { "query": "foo bar" }

+ Response 200 (application/json)

    {
      "links": {
        "self": "http://api.catarse.me/users"
      },
      data: [
        {
          "id": 1,
          "email":"foo@bar.com",
          "name":"Foo Bar",
          "admin":false,
          "sign_in_count":2,
          "deactivated_at":null
          "uploaded_image":null,
          "cover_image":null,
          "permalink":null,
          "subscribed_to_project_posts":true,
          "created_at":"2014-08-20T16:43:56.298595",
          "updated_at":"2014-08-21T00:58:27.685419",
          "html_url":"http://www.catarse.me/users/1-foo-bar",
          "relantionships": {
            "contributions": {
              "links": {
                "self": "http://www.catarse.me/contributions/?user_id=1"
              }
            }
          },
          "links": {
            "self":"http://api.catarse.me/users/1"
          }
        }
      ]
    }
        

+ Response 401 (application/json)

        {}

## User [/users/{id}]
A single User object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a User [GET]
+ Request

    + Header

            Authorization: Token your-token-here

+ Response 200 (application/json)

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Update a User [PATCH]
+ Request

    + Header

            Authorization: Token your-token-here

+ Response 204 (application/json)

### Remove a User [DELETE]
+ Request

    + Header

            Authorization: Token your-token-here

+ Response 204
